# docker-compose.dev.yml
services:
  db:
    image: postgres:16-alpine
    container_name: demoecommerce-db-dev
    environment:
      POSTGRES_DB: demoecommerce
      POSTGRES_USER: demo
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - db-data-dev:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      target: dev          # ðŸŸ¢ usamos la etapa dev del Dockerfile.backend
    container_name: demoecommerce-backend-dev
    working_dir: /var/www
    volumes:
      - ./backend:/var/www
    env_file:
      - ./backend/.env
    depends_on:
      - db

  nginx-api:
    image: nginx:1.27-alpine
    container_name: demoecommerce-nginx-api-dev
    ports:
      - "8080:80"          # API accesible en http://localhost:8080
    volumes:
      - ./backend:/var/www
      - ./docker/nginx/nginx.api.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend

  frontend:
    build:
      context: ./frontend
      target: dev
    container_name: demoecommerce-frontend-dev
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "5173:5173"
    depends_on:
      - nginx-api
    environment:
      - VITE_API_URL=http://localhost:8080/api



volumes:
  db-data-dev:
